name: Lint Code Base

on: [push, pull_request]

env:
    VALIDATE_HTML: false
    GITHUB_TOKEN: ${{github.token}} 

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Lint Code Base
        uses: github/super-linter@v4
